### ISSUE TITLE
Nested Keys

### ISSUE THREAD

**Issue by tef** [imbal/safeyaml#4]
```
- name: value
- name: value
```

Is *very* popular

**Comment by marksutherland** [comment]
Yup, kubernetes manifest files seem to love them, for example. Here's a simple case and the output it causes:

```
parent:
  - child: value
    another: please
```

```
➭ ./safeyaml.py --fix example.txt
['example.txt']:2:5:The parser is trying its very best but could only make out 'child', but there is other junk on that line. You fix it.
```

**Comment by aanand** [comment]
We have 3 options in the face of any particular practice:

1. Reject outright
2. Fix when `--fix` is passed
3. Accept

The problem with a map inside a list starting on the same line is that, in the one-element case, it's very easy to confuse with a string. We had this exact problem in Compose, where people would put a space in their volume mount:

```yaml
web:
  build: web
  volumes:
    - web:/web

chat:
  build: chat
  volumes:
    - chat: /chat
```

Above, `web:/web` is a string, and `chat: /chat` is a map. A linter therefore can't make a safe call as to the user's intention.

Supposing we went with 2, the output of running `safeyaml --fix` on the above would be:

```yaml
web:
  build: "web"
  volumes:
    - "web:/web"

chat:
  build: chat
  volumes:
    -
      chat: "/chat"
```

Whereas if we went with 3, it would be:

```yaml
web:
  build: "web"
  volumes:
    - "web:/web"

chat:
  build: "chat"
  volumes:
    - chat: "/chat"
```

On aesthetic grounds, I think I've argued myself around to option 3 - accept them. The rewritten version is equally clear in either case.
